# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fy < Formula
  desc "A command-line translation tool"
  homepage "https://github.com/xwjdsh/fy"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/fy/releases/download/v0.5.0/fy_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "8918f94d736cef8e38784fa3c253f14403e1f434fc8c58826f8783874b2cf5eb"

      def install
        bin.install "fy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xwjdsh/fy/releases/download/v0.5.0/fy_0.5.0_Darwin_arm64.tar.gz"
      sha256 "ea87e10319b75ee503df656762e4dc50337669111aaa0d798fab3a3724994142"

      def install
        bin.install "fy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/fy/releases/download/v0.5.0/fy_0.5.0_Linux_x86_64.tar.gz"
      sha256 "2ead95125a80a72fa2da81753427460069ed9a60495284a58eb60f3a0d718f0c"

      def install
        bin.install "fy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xwjdsh/fy/releases/download/v0.5.0/fy_0.5.0_Linux_arm64.tar.gz"
      sha256 "8d037b2ce2ba08d811e8c0026660eadcd60dd105bcfeb07229a904757e9c07f9"

      def install
        bin.install "fy"
      end
    end
  end
end
