# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunar < Formula
  desc "A command-line tool for searching and converting the lunar calendar"
  homepage "https://github.com/xwjdsh/lunar"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/lunar/releases/download/v0.1.0/lunar_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "63775ac7976a1649fd96bb3f4103eb51c83d2e3618a9c4ba11efbf03f443f1df"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xwjdsh/lunar/releases/download/v0.1.0/lunar_0.1.0_Darwin_arm64.tar.gz"
      sha256 "f7981877f951f6ba83943c3a3694911ed4eadfc3c3a2396ca90c49c6a8f91ccd"

      def install
        bin.install "lunar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/lunar/releases/download/v0.1.0/lunar_0.1.0_Linux_x86_64.tar.gz"
      sha256 "b6808d4c22d90453fabcdc71961e67c65752ec8db5e2a30841d2339f56e26215"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xwjdsh/lunar/releases/download/v0.1.0/lunar_0.1.0_Linux_arm64.tar.gz"
      sha256 "1c48b8f5f39b65ba367e8e7736032e46717da741232688d8b9673862b425d072"

      def install
        bin.install "lunar"
      end
    end
  end
end
