# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manssh < Formula
  desc "Manage your ssh alias configs easily"
  homepage "https://github.com/xwjdsh/manssh"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/manssh/releases/download/v0.5.3/manssh_0.5.3_Darwin_x86_64.tar.gz"
      sha256 "490dad6fda49366a794191cb946f4a621bce5713600896abe684ccd634575977"

      def install
        bin.install "manssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xwjdsh/manssh/releases/download/v0.5.3/manssh_0.5.3_Darwin_arm64.tar.gz"
      sha256 "aa5fc601425bcfbf7f3549ab3c5d46b27a079da2f793825624dafcc965251a1e"

      def install
        bin.install "manssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xwjdsh/manssh/releases/download/v0.5.3/manssh_0.5.3_Linux_x86_64.tar.gz"
      sha256 "4b849f7df06087e4c2c64b6a680c5b50738fe31f53593f8263ac243bedf12025"

      def install
        bin.install "manssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xwjdsh/manssh/releases/download/v0.5.3/manssh_0.5.3_Linux_arm64.tar.gz"
      sha256 "6b965d9f6012c43220f2804a3a7cb9cec59c7603d7edde65b6780beeb6f38ac0"

      def install
        bin.install "manssh"
      end
    end
  end
end
